- name: Create Docker cli-plugins directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install Docker Buildx
  get_url:
    url: "https://github.com/docker/buildx/releases/download/{{ buildx_version }}/buildx-{{ buildx_version }}.linux-amd64"
    dest: /usr/local/lib/docker/cli-plugins/docker-buildx
    mode: '0755'